services:
  postgres:
    image: postgres:16-alpine
    container_name: hello-cucumber-postgres
    environment:
      POSTGRES_DB: cucumber_db
      POSTGRES_USER: cucumber_user
      POSTGRES_PASSWORD: cucumber_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U cucumber_user -d cucumber_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
